from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import replace
from datetime import datetime
from pathlib import Path
from typing import Dict, List

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from screener.backtest.engine import BacktestConfig, run_backtest
from screener.backtest.output import (
    build_summary_payload,
    format_summary_table,
    write_summary_json,
    write_trade_log,
)
from screener.backtest.portfolio import PortfolioConfig, simulate_portfolio
from screener.backtest.stats import summarize_trades
from screener.config import Settings
from screener.universe import load_universe

TEST_SYMBOLS_21 = [
    # Technology
    "AAPL",
    "MSFT",
    "NVDA",
    # Communication Services
    "GOOGL",
    "META",
    "NFLX",
    # Consumer Discretionary
    "AMZN",
    "TSLA",
    "HD",
    # Health Care
    "LLY",
    "JNJ",
    "UNH",
    # Financials
    "JPM",
    "BAC",
    "GS",
    # Industrials
    "CAT",
    "HON",
    "GE",
    # Energy
    "XOM",
    "CVX",
    "SLB",
]


def setup_logger() -> logging.Logger:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
    return logging.getLogger("backtest")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run dual-engine swing screener backtest")
    parser.add_argument("--engine", choices=["bull", "weak", "both"], default="both")
    parser.add_argument("--start-date", default="2020-01-01")
    parser.add_argument("--end-date", default="2024-12-31")
    parser.add_argument("--symbol-mode", choices=["test", "full"], default="test")

    # Portfolio simulator assumptions
    parser.add_argument("--initial-capital", type=float, default=10000.0)
    parser.add_argument("--max-positions", type=int, default=5)
    parser.add_argument("--slippage-pct", type=float, default=0.0005)
    parser.add_argument("--commission-per-side", type=float, default=0.32)
    parser.add_argument("--monthly-dd-limit-pct", type=float, default=6.0)
    parser.add_argument("--monthly-risk-per-trade-pct", type=float, default=1.0)
    parser.add_argument("--risk-free-rate-annual", type=float, default=0.0)
    parser.add_argument("--trading-days-per-year", type=int, default=252)

    return parser.parse_args()


def _lookback_days(start_date: str, end_date: str, warmup_days: int = 260) -> int:
    """Compute download lookback from *today* so historical windows are not truncated.

    fetch_prices() downloads from (now - lookback_days), so for historical backtests
    we must ensure lookback reaches at least start_date + warmup from today's date,
    not merely (end_date - start_date).
    """
    start = datetime.strptime(start_date, "%Y-%m-%d")
    end = datetime.strptime(end_date, "%Y-%m-%d")
    now = datetime.now()

    # Backtest period length (legacy minimum baseline).
    span_days = max(0, (end - start).days)
    # Distance from today back to requested start date.
    days_to_start = max(0, (now - start).days)

    required = max(span_days, days_to_start) + warmup_days
    return max(800, int(required))


def _resolve_symbols(settings: Settings, symbol_mode: str) -> List[str]:
    if symbol_mode == "test":
        return sorted({s.strip().upper() for s in TEST_SYMBOLS_21 if s.strip()})
    universe = load_universe(settings.universe_file)
    return sorted({item.yf_symbol for item in universe})


def _portfolio_assumptions_dict(config: PortfolioConfig) -> Dict[str, object]:
    return {
        "initial_capital": config.initial_capital,
        "max_positions": config.max_positions,
        "slippage_pct_each_side": config.slippage_pct_each_side,
        "commission_per_side": config.commission_per_side,
        "monthly_drawdown_limit_pct": config.monthly_drawdown_limit_pct,
        "monthly_risk_per_trade_pct": config.monthly_risk_per_trade_pct,
        "risk_free_rate_annual": config.risk_free_rate_annual,
        "trading_days_per_year": config.trading_days_per_year,
        "share_rounding": config.share_rounding,
        "entry_priority": config.entry_priority,
        "monthly_drawdown_rule": "halt_new_entries_if_equity_below_month_start_equity_threshold",
    }


def _build_methodology_meta(config: PortfolioConfig) -> Dict[str, object]:
    return {
        "entry_rules": "Signals generated by bull/weak engines; entries at next session open when signal date regime matches engine.",
        "exit_rules": "Per-candidate TP/SL logic from strategy; exits use planned exit date close in portfolio simulation.",
        "regime_filter_logic": "Regime filter uses SPY vs SMA200: Bull engine above SMA200, Weak engine below SMA200.",
        "next_open_entry": "Enabled",
        "signal_price_vs_pnl_price": "Signals use adjusted-close indicators; portfolio fills use raw open/close with slippage and commissions.",
        "portfolio_assumptions": _portfolio_assumptions_dict(config),
    }


def main() -> int:
    args = parse_args()
    logger = setup_logger()

    settings = Settings()
    backtest_settings = replace(
        settings,
        lookback_calendar_days=_lookback_days(args.start_date, args.end_date),
    )

    symbols = _resolve_symbols(backtest_settings, args.symbol_mode)
    config = BacktestConfig(
        start_date=args.start_date,
        end_date=args.end_date,
        engine=args.engine,
        warmup_bars=200,
    )

    portfolio_cfg = PortfolioConfig(
        initial_capital=float(args.initial_capital),
        max_positions=int(args.max_positions),
        slippage_pct_each_side=float(args.slippage_pct),
        commission_per_side=float(args.commission_per_side),
        monthly_drawdown_limit_pct=float(args.monthly_dd_limit_pct),
        monthly_risk_per_trade_pct=float(args.monthly_risk_per_trade_pct),
        risk_free_rate_annual=float(args.risk_free_rate_annual),
        trading_days_per_year=int(args.trading_days_per_year),
    )

    result = run_backtest(
        symbols=symbols,
        settings=backtest_settings,
        config=config,
        logger=logger,
    )

    portfolio_result = simulate_portfolio(
        candidates=result.candidates,
        prices_by_symbol=result.prices,
        benchmark_symbol=backtest_settings.benchmark_symbol,
        start_date=args.start_date,
        end_date=args.end_date,
        config=portfolio_cfg,
    )

    trades_csv_path = write_trade_log(portfolio_result.executed_trades, out_dir="data/backtests")
    stats = summarize_trades(portfolio_result.executed_trades)

    portfolio_payload = {
        "assumptions": _portfolio_assumptions_dict(portfolio_cfg),
        "metrics": portfolio_result.metrics,
        "curve": {
            "dates": portfolio_result.equity_curve.get("date", pd.Series(dtype=object)).astype(str).tolist(),
            "equity": portfolio_result.equity_curve.get("equity", pd.Series(dtype=float)).astype(float).round(4).tolist(),
            "drawdown_pct": portfolio_result.equity_curve.get("drawdown_pct", pd.Series(dtype=float)).astype(float).round(4).tolist(),
        },
        "monthly_returns": portfolio_result.monthly_returns.to_dict(orient="records"),
    }

    diagnostics = dict(result.diagnostics)
    counts = dict((diagnostics.get("counts") or {}))
    counts["portfolio_executed_trades"] = int(len(portfolio_result.executed_trades))
    counts["portfolio_rejected_entries"] = int(portfolio_result.metrics.get("rejected_entries", 0) or 0)
    counts["portfolio_months_halted"] = int(portfolio_result.metrics.get("months_halted", 0) or 0)
    diagnostics["counts"] = counts

    summary_payload = build_summary_payload(
        engine=args.engine,
        start_date=args.start_date,
        end_date=args.end_date,
        symbol_mode=args.symbol_mode,
        symbol_count=len(symbols),
        benchmark_symbol=backtest_settings.benchmark_symbol,
        stats=stats,
        diagnostics=diagnostics,
        trades_path=trades_csv_path,
        portfolio=portfolio_payload,
        methodology=_build_methodology_meta(portfolio_cfg),
    )
    write_summary_json(summary_payload, path="docs/data/backtest_summary.json")

    print(format_summary_table(summary_payload))
    print(f"Trade log CSV: {str(trades_csv_path).replace('\\\\', '/')}")
    print("Summary JSON: docs/data/backtest_summary.json")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
